class AppConstants {
  static const String appName = 'NutriScan';
  static const String appTagline =
      'Assistente inteligente para gestão de distúrbios digestivos';

  // Backend API — selecionado automaticamente conforme a plataforma.
  // Veja core/api_config.dart
  static const String openFoodFactsBaseUrl =
      'https://world.openfoodfacts.org/api/v2';

  // Categorias de distúrbios digestivos suportadas
  static const List<String> digestiveDisorders = [
    'Intolerância à Lactose',
    'Doença Celíaca',
    'Síndrome do Intestino Irritável (SII)',
    'Doença de Crohn',
    'Colite Ulcerativa',
    'Alergia à Proteína do Leite (APLV)',
    'Alergia ao Ovo',
    'Alergia ao Amendoim',
    'Alergia à Soja',
    'Intolerância à Frutose',
    'FODMAP Sensível',
    'Refluxo Gastroesofágico (DRGE)',
  ];

  /// Mapeia distúrbio → ingredientes/termos problemáticos.
  /// O matching usa fronteira de palavra e ignora acentos.
  static const Map<String, List<String>> problematicIngredients = {
    'Intolerância à Lactose': [
      'leite',
      'lactose',
      'soro de leite',
      'soro do leite',
      'soro lacteo',
      'caseina',
      'caseinato',
      'manteiga',
      'creme de leite',
      'queijo',
      'iogurte',
      'nata',
      'whey',
      'lactalbumina',
      'leite em po',
      'leite condensado',
    ],
    'Doença Celíaca': [
      'trigo',
      'gluten',
      'cevada',
      'centeio',
      'malte',
      'farinha de trigo',
      'amido de trigo',
      'semolina',
      'espelta',
      'kamut',
      'triticale',
      'farelo de trigo',
      'germen de trigo',
      'extrato de malte',
      'cerveja',
    ],
    'Síndrome do Intestino Irritável (SII)': [
      'lactose',
      'frutose',
      'sorbitol',
      'manitol',
      'xilitol',
      'maltitol',
      'inulina',
      'frutano',
      'galactano',
      'cebola',
      'alho',
      'gluten',
    ],
    'Doença de Crohn': [
      'lactose',
      'gluten',
      'cafeina',
      'alcool',
      'gordura trans',
      'gordura hidrogenada',
      'corante artificial',
      'edulcorante',
    ],
    'Colite Ulcerativa': [
      'lactose',
      'gluten',
      'cafeina',
      'alcool',
      'pimenta',
      'gordura trans',
      'conservante',
      'aromatizante artificial',
    ],
    'Alergia à Proteína do Leite (APLV)': [
      'leite',
      'caseina',
      'caseinato',
      'soro de leite',
      'whey',
      'manteiga',
      'creme de leite',
      'queijo',
      'iogurte',
      'lactoalbumina',
      'lactoglobulina',
    ],
    'Alergia ao Ovo': [
      'ovo',
      'ovos',
      'clara de ovo',
      'gema',
      'albumina',
      'ovoalbumina',
      'lecitina de ovo',
      'lisozima',
    ],
    'Alergia ao Amendoim': [
      'amendoim',
      'pasta de amendoim',
      'oleo de amendoim',
      'arachis',
    ],
    'Alergia à Soja': [
      'soja',
      'lecitina de soja',
      'proteina de soja',
      'oleo de soja',
      'extrato de soja',
      'molho de soja',
      'shoyu',
      'tofu',
    ],
    'Intolerância à Frutose': [
      'frutose',
      'xarope de milho',
      'xarope de glicose-frutose',
      'mel',
      'agave',
      'sorbitol',
      'xarope de frutose',
      'sacarose',
    ],
    'FODMAP Sensível': [
      'frutose',
      'lactose',
      'sorbitol',
      'manitol',
      'xilitol',
      'maltitol',
      'inulina',
      'frutano',
      'oligofrutose',
      'cebola',
      'alho',
      'trigo',
    ],
    'Refluxo Gastroesofágico (DRGE)': [
      'cafeina',
      'chocolate',
      'hortela',
      'menta',
      'pimenta',
      'tomate',
      'cebola',
      'alho',
      'alcool',
      'gordura hidrogenada',
    ],
  };
}
